name: appliance_manager
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter 
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
