name: applianceCare 
description: "This application will help ."
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.1
  flutter_dotenv: ^5.0.2  # Use the latest version
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter 
  http: ^1.3.0
  logger: ^2.5.0
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  image: ^4.5.2
  path_provider: ^2.1.5
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  flutter_launcher_icons: ^0.14.3
  csv: ^6.0.0
  webview_flutter: ^4.10.0
  flutter_local_notifications: ^19.0.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/appicon/
    - .env


flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon/ApplianceManagerIcon.png"
  adaptive_icon_background: "#000000" # or #FFFFFF (or transparent)

