name: appliance_manager
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.1
  flutter_dotenv: ^5.0.2  # Use the latest version
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter 
  http: ^1.3.0
  logger: ^2.5.0
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  image: ^4.5.2
  path_provider: ^2.1.5
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

